### ISSUE TITLE
Can`t start logging on CLI!

### ISSUE THREAD

**Issue by chrisu3050** [peterh/pyobd#7]
Always getting this Error:

> root@at-stp-05:~/pyobd-pi# python obd_recorder.py
> Logging item: Engine RPM
> Logging item: Vehicle Speed
> Logging item: Throttle Position
> Logging item: Calc Load Value
> Logging item: Fuel System Stat
> ['/dev/rfcomm0']
> Opening interface (serial port)
> Interface successfully /dev/rfcomm0 opened
> Connecting to ECU...
> atz response:CONNECTED?
> ate0 response:ELM327 v1.5
> 0100 response:0100CAN ERROR
> Connected to /dev/rfcomm0
> Logging started
> Traceback (most recent call last):
>   File "obd_recorder.py", line 103, in <module>
>     o.record_data()
>   File "obd_recorder.py", line 67, in record_data
>     (name, value, unit) = self.port.sensor(index)
>   File "/root/pyobd-pi/obd_io.py", line 226, in sensor
>     r = self.get_sensor_value(sensor)
>   File "/root/pyobd-pi/obd_io.py", line 215, in get_sensor_value
>     data = sensor.value(data)
>   File "/root/pyobd-pi/obd_sensors.py", line 42, in rpm
>     code = hex_to_int(code)
>   File "/root/pyobd-pi/obd_sensors.py", line 26, in hex_to_int
>     i = eval("0x" + str, {}, {})
>   File "<string>", line 1
>     0x1CANERROR
>               ^
> SyntaxError: unexpected EOF while parsing

Even searched in Source-Code, but can't find any error there.

What have I wrong?

I am working on a Raspberry Pi 3B, with the newest Raspian-Version over CLI.

thanks!

**Comment by peterh** [comment]
It says CAN ERROR, so it sounds like an error talking to the CAN bus of the vehicle, maybe. Have you checked the vehicle connection to make sure it's solid?

pyobd isn't my code. This is just a convenient mirror. I'm afraid I cannot help any further.
